/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Question {
  'questionWord' : string,
  'correctAnswerIndex' : bigint,
  'options' : Array<string>,
}
export interface UserStats {
  'wordsLearned' : bigint,
  'totalAttempts' : bigint,
  'correctAnswers' : bigint,
}
export interface _SERVICE {
  'addWord' : ActorMethod<
    [string, string, string, string, bigint, string],
    undefined
  >,
  'getPracticeQuestion' : ActorMethod<[], Question>,
  'getUserStats' : ActorMethod<[Principal], UserStats>,
  'submitAnswer' : ActorMethod<[boolean], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];