/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Question = IDL.Record({
  'questionWord' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const UserStats = IDL.Record({
  'wordsLearned' : IDL.Nat,
  'totalAttempts' : IDL.Nat,
  'correctAnswers' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addWord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'getPracticeQuestion' : IDL.Func([], [Question], []),
  'getUserStats' : IDL.Func([IDL.Principal], [UserStats], ['query']),
  'submitAnswer' : IDL.Func([IDL.Bool], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Question = IDL.Record({
    'questionWord' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const UserStats = IDL.Record({
    'wordsLearned' : IDL.Nat,
    'totalAttempts' : IDL.Nat,
    'correctAnswers' : IDL.Nat,
  });
  
  return IDL.Service({
    'addWord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'getPracticeQuestion' : IDL.Func([], [Question], []),
    'getUserStats' : IDL.Func([IDL.Principal], [UserStats], ['query']),
    'submitAnswer' : IDL.Func([IDL.Bool], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };